//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignments.Core.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignments.Core.Assets.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking object.
        /// </summary>
        internal static string BlockingObject {
            get {
                return ResourceManager.GetString("BlockingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking objects.
        /// </summary>
        internal static string BlockingObjects {
            get {
                return ResourceManager.GetString("BlockingObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----------------------------------------.
        /// </summary>
        internal static string CMD_LineSeperator {
            get {
                return ResourceManager.GetString("CMD_LineSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine thread id.
        /// </summary>
        internal static string EngineThreadId {
            get {
                return ResourceManager.GetString("EngineThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hadle.
        /// </summary>
        internal static string Hadle {
            get {
                return ResourceManager.GetString("Hadle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is 64 bit process (AMD64).
        /// </summary>
        internal static string Is64BitProcess {
            get {
                return ResourceManager.GetString("Is64BitProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is managed thread.
        /// </summary>
        internal static string IsManagedThread {
            get {
                return ResourceManager.GetString("IsManagedThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel object name.
        /// </summary>
        internal static string KernelObjectName {
            get {
                return ResourceManager.GetString("KernelObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel object type name.
        /// </summary>
        internal static string KernelObjectTypeName {
            get {
                return ResourceManager.GetString("KernelObjectTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed object address.
        /// </summary>
        internal static string ManagedObjectAddress {
            get {
                return ResourceManager.GetString("ManagedObjectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Thread Id.
        /// </summary>
        internal static string OS_ThreadId {
            get {
                return ResourceManager.GetString("OS_ThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special.
        /// </summary>
        internal static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        internal static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Info.
        /// </summary>
        internal static string Thread_Info {
            get {
                return ResourceManager.GetString("Thread_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected architecture..
        /// </summary>
        internal static string UnexpectedArchitecture {
            get {
                return ResourceManager.GetString("UnexpectedArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait reason.
        /// </summary>
        internal static string WaitReason {
            get {
                return ResourceManager.GetString("WaitReason", resourceCulture);
            }
        }
    }
}
